Repository amberframework/garnet-spec, pull requests merged in 2018-06, with the labels that each got.

#14 Fix Travis CI build
  .travis.yml
Labels: kind:bug, pr:needs-review

#13 Don't override Content-Type if already given
  spec/controller/test_spec.cr
  src/garnet_spec/controller/test.cr
Labels: kind:bug, pr:needs-review

#15 hack update to point to an updated shard
  shard.yml
Labels: pr:needs-review

#17 Update to point to new version of selenium driver
  shard.yml
Labels: kind:enhancement

#18 tick to v0.2.1
  shard.yml
  src/garnet_spec/version.cr
Labels: kind:enhancement
